public enum BuildingTypes
{
    None,
    MainBase,
    Windmill,
    LumberingShack,
    StoneQuarry,
    SteelFoundry,
    SulfurMounds,
    GemMine,
    Catapult,
    SicFactory,
    CatShelter,
    Marketplace,
    TrainingGrounds,
    MageGuild,
    Portal,
    FloofAcademy
}