    public enum AudioLibrarySounds {
        Select,
        SpawnCat,
        WinBattle,
        Haste,
        Sand,
        Heal,
        Box,
        Pounce,
        Laser,
        Shield,
        Teleport,
        Void,
        Bewitch,
        Slash,
        Attack,
        Pass,
        Camouflage,
        Castle,
        Sawmill,
        StoneMine,
        Steel,
        Gems,
        Sulfur,
        Windmill,
        Move
    }
    public enum AudioLibraryMusic {
    }
